apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} \[%{LOGLEVEL:level}\] %{GREEDYDATA:message_text}" }
      }
      date {
        match => [ "timestamp", "ISO8601" ]
      }
      mutate {
        remove_field => [ "host", "@version" ]
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch-service:9200"]
        index => "sim-logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
